<a href="https://colab.research.google.com/github/ryali93/UNMSM_programacion2019-1/blob/master/jupyter/clase09_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a NumPy

Hasta ahora hemos visto los tipos de datos más básicos que nos ofrece Python: integer, real, complex, boolean, list, tuple y demás.
En este notebook nos adentraremos en el paquete NumPy: aprenderemos a crear distintos arrays y a operar con ellos.

## ¿Qué es un array? 

Un array es un __bloque de memoria que contiene elementos del mismo tipo__. Básicamente:

* nos _recuerdan_ a los vectores, matrices, tensores...
* podemos almacenar el array con un nombre y acceder a sus __elementos__ mediante sus __índices__.
* ayudan a gestionar de manera eficiente la memoria y a acelerar los cálculos.


---

| Índice     | 0     | 1     | 2     | 3     | ...   | n-1   | n  |
| ---------- | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| Valor      | 2.1   | 3.6   | 7.8   | 1.5   | ...   | 5.4   | 6.3 |

---

__¿Qué solemos guardar en arrays?__

* Vectores y matrices.
* Datos de experimentos:
    - En distintos instantes discretos.
    - En distintos puntos del espacio.
* Resultado de evaluar funciones con los datos anteriores.
* Discretizaciones para usar algoritmos de: integración, derivación, interpolación...


## ¿Qué es NumPy?

NumPy es un paquete fundamental para la programación científica que __proporciona un objeto tipo array__ para almacenar datos de forma eficiente y una serie de __funciones__ para operar y manipular esos datos.
Para usar NumPy lo primero que debemos hacer es importarlo:

In [0]:
import numpy as np
#para ver la versión que tenemos instalada:
np.__version__

'1.16.2'

## Nuestro primer array

¿No decíamos que Python era fácil? Pues __creemos nuestros primeros arrays__:

In [0]:
import numpy as np

In [0]:
# Array de una dimensión
mi_primer_array = np.array([1, 2, 3, 4]) 
mi_primer_array

array([1, 2, 3, 4])

In [0]:
# Podemos usar print
print(mi_primer_array)

[1 2 3 4]


In [0]:
# Comprobar el tipo de mi_primer_array
type(mi_primer_array)

numpy.ndarray

In [0]:
# Comprobar el tipo de datos que contiene
mi_primer_array.dtype

dtype('int64')

Los arrays de una dimensión se crean pasándole una lista como argumento a la función `np.array`. Para crear un array de dos dimensiones le pasaremos una _lista de listas_:

In [0]:
# Array de dos dimensiones
mi_segundo_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

<div class="alert alert-info">Podemos continuar en la siguiente línea usando `\`, pero no es necesario escribirlo dentro de paréntesis o corchetes</div>

Esto sería una buena manera de definirlo, de acuerdo con el [PEP 8 (indentation)](http://legacy.python.org/dev/peps/pep-0008/#indentation):

In [0]:
mi_segundo_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ]) 

### Funciones y constantes de NumPy

Hemos dicho que NumPy también incorporá __funciones__. Un ejemplo sencillo:

In [0]:
mi_primer_array

array([1, 2, 3, 4])

In [0]:
# Suma
np.sum(mi_primer_array)

10

In [0]:
# Máximo
np.max(mi_primer_array)

4

In [0]:
mi_segundo_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
np.max(mi_segundo_array)

9

In [0]:
np.max(mi_segundo_array,axis=0)

array([7, 8, 9])

In [0]:
np.max(mi_segundo_array,axis=1)

array([3, 6, 9])

In [0]:
# Seno
np.sin(mi_segundo_array)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

Y algunas __constantes__ que podemos neccesitar:

In [0]:
np.pi, np.e

(3.141592653589793, 2.718281828459045)

### Atributos de un array

In [0]:
### Número de dimensiones de un array

In [0]:
mi_primer_array.ndim

1

In [0]:
mi_segundo_array.ndim

2

In [0]:
### Tamaño de cada dimensión

In [0]:
mi_primer_array.shape

(4,)

In [0]:
mi_segundo_array.shape

(3, 3)

In [0]:
### Número de elementos de un array

In [0]:
mi_primer_array.size

4

In [0]:
mi_segundo_array.size

9

## Funciones para crear arrays

Hemos visto que la función `np.array()` nos permite crear arrays con los valores que nosotros introduzcamos manualmente a través de listas.

#### array de ceros

In [0]:
# En una dimensión
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
# En dos dimensiones
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

<div class="alert alert-info"><strong>Nota:</strong> 
En el caso 1D es válido tanto `np.zeros([5])` como `np.zeros(5)` (sin los corchetes), pero no lo será para el caso nD
</div>

#### array "vacío"

In [0]:
np.empty(10)

array([4.65303026e-310, 0.00000000e+000, 6.94299715e-310, 6.94301399e-310,
       6.94299671e-310, 6.94299671e-310, 6.94299714e-310, 0.00000000e+000,
       6.94300540e-310, 6.94299714e-310])

<div class="alert alert-error"><strong>Importante:</strong> 
El array vacío se crea en un tiempo algo inferior al array de ceros. Sin embargo, el valor de sus elementos será arbitrario y dependerá del estado de la memoria. Si lo utilizas asegúrate de que luego llenas bien todos sus elementos porque podrías introducir resultados erróneos.
</div>

#### array de unos

In [0]:
np.ones([3, 2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

<div class="alert alert-info"><strong>Nota:</strong> 
Otras funciones muy útiles son `np.zeros_like` y `np.ones_like`. Usa la ayuda para ver lo que hacen si lo necesitas.
</div>

#### array identidad

In [0]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<div class="alert alert-info"><strong>Nota:</strong> 
También puedes probar `np.eye()` y `np.diag()`.
</div>

### Rangos

#### np.arange

NumPy, dame __un array que vaya de 0 a 5__:

In [0]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

__Mira con atención el resultado anterior__, ¿hay algo que deberías grabar en tu cabeza para simpre?
__El último elemento no es 5 sino 4__

NumPy, dame __un array que vaya de 0 a 10, de 3 en 3__:

In [0]:
np.arange(0, 11, 3)

array([0, 3, 6, 9])

#### np.linspace

Si has tenido que usar MATLAB alguna vez, seguro que esto te suena:

In [0]:
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

En este caso sí que se incluye el último elemento.

<div class="alert alert-info"><strong>Nota:</strong> 
También puedes probar `np.logspace()`
</div>

### reshape

Con `np.arange()` es posible crear "vectores" cuyos elementos tomen valores consecutivos o equiespaciados, como hemos visto anteriormente. ¿Podemos hacer lo mismo con "matrices"? Pues sí, pero no usando una sola función. Imagina que quieres crear algo como esto:

\begin{pmatrix}
    1 & 2 & 3\\ 
    4 & 5 & 6\\
    7 & 8 & 9\\
    \end{pmatrix}
    
* Comenzaremos por crear un array 1d con los valores $(1,2,3,4,5,6,7,8,9)$ usando `np.arange()`.
* Luego le daremos forma de array 2d. con `np.reshape(array, (dim0, dim1))`.

In [0]:
a = np.arange(1, 10)
M = np.reshape(a, [3, 3])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
# También funciona como método
N = a.reshape([3,3])
N

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<div class="alert alert-info"><strong>Nota:</strong> 
No vamos a entrar demasiado en qué son los métodos, pero debes saber que están asociados a la programación orientada a objetos y que en Python todo es un objeto. Lo que debes pensar es que son unas funciones especiales en las que el argumento más importante (sobre el que se realiza la acción) se escribe delante seguido de un punto. Por ejemplo: `<objeto>.método(argumentos)`
</div>

## Operaciones

### Operaciones elemento a elemento

Ahora que pocas cosas se nos escapan de los arrays, probemos a hacer algunas operaciones. El funcionamiento es el habitual en FORTRAN y MATLAB y poco hay que añadir:

In [0]:
#crear un arra y y sumarle un número
arr = np.arange(11)
arr + 55

array([55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65])

In [0]:
#multiplicarlo por un número
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [0]:
#elevarlo al cuadrado
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [0]:
#calcular una función
np.tanh(arr)

array([0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ,
       0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997,
       1.        ])

<div class="alert alert-info"><strong>Entrenamiento:</strong> 
Puedes tratar de comparar la diferencia de tiempo entre realizar la operación en bloque, como ahora, y realizarla elemento a elemento, recorriendo el array con un bucle.
</div>

__Si las operaciones involucran dos arrays también se realizan elemento a elemento__

In [0]:
#creamos dos arrays
arr1 = np.arange(0, 11)
arr2 = np.arange(20, 31)

In [0]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [0]:
#los sumamos
arr1 + arr2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [0]:
#multiplicamos
arr1 * arr2

array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

#### Comparaciones

In [0]:
# >,<
arr1 > arr2

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [0]:
# ==
arr1 == arr2 # ¡ojo! los arrays son de integers, no de floats

array([False, False, False, False, False, False, False, False, False,
       False, False])

___Hemos aprendido:___

* A usar las principales funciones para crear arrays.
* A operar con arrays.


Algunos enlaces:

Algunos enlaces en Pybonacci:

* [Cómo crear matrices en Python con NumPy](http://pybonacci.wordpress.com/2012/06/11/como-crear-matrices-en-python-con-numpy/).
* [Números aleatorios en Python con NumPy y SciPy](http://pybonacci.wordpress.com/2013/01/11/numeros-aleatorios-en-python-con-numpy-y-scipy/).


Algunos enlaces en otros sitios:

* [100 numpy exercises](http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html).
* [NumPy and IPython SciPy 2013 Tutorial](http://conference.scipy.org/scipy2013/tutorial_detail.php?id=100).
* [NumPy and SciPy documentation](http://docs.scipy.org/doc/).