<a href="https://colab.research.google.com/github/ryali93/UNMSM_programacion2019-1/blob/master/jupyter/clase09_numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 9. Numpy

**Numpy** es un paquete especializado en computación científica. Contiene tipos de datos, módulos, clases y funciones que posibilitan la creación y manejo de matrices (arrays) de n-dimensiones.
Las ventajas más importante de usar **Numpy** son:

* **Es multiplataforma**
* **Potente** conjunto de librerías.

## 9.1. Matrices

En matemática, una matriz es un arreglo bidimensional de números. Dado que puede definirse tanto la suma como el producto de matrices. En Python una matriz (array) es un objeto y tiene propiedades (métodos) como la mutabilidad. Acontinuación se define la matriz **A** de **m** filas y **n** columnas.
Es importante tener  presente que en Python la indexación siempre inicia en **cero**, ya sea en tuplas, listas o arrays (vectores ó matrices).


$$
\mathbf{A}=
\left| \begin{array}{ccc}
  a_{0,0} & a_{0,1} &  a_{0,2} &  \dots &  a_{0,n} \\
  a_{1,0} & a_{1,1} &  a_{1,2} &  \dots &   a_{1,n} \\
   \vdots  &  \vdots  &   \vdots  &  \vdots &   \vdots \\
  a_{m,0} & a_{m,1} &  a_{m,2} &  \dots &   a_{m,n} \\
  \end{array}\right|_{mxn} = \mathbf{A}_{m\times n}
$$

> Acontinuación se muestra una tabla con los métodos que ofrece **numpy** para trabajar con arreglos/matrices.

|Método| Resultado| 
|:-----|:-------------|
|**A**.shape   | Tupla con las dimensiones | 
|**A**.ndim    | Número de dimensiones  |
|**A**.size    | Número de elementos  |
|**A**.itemsize| Tamaño de uno de los elementos en bytes  |
|**A**.nbytes  | Tamaño total ocupado por los elementos  |
|**A**.dtype   |  Tipo de dato de los elementos |
|**A**.real    | Parte real  |
|**A**.imag    | Parte imaginaria  |

Acontinuación trataremos:

* Arreglos de una dimensión (1D).
* Arreglos de n-dimensiones (nD).

### Arreglos de una dimensión (1D)
> Para empezar crearemos los arreglos  $\mathbf{x1D}_{1\times n}$ y $\mathbf{y1D}_{1\times n}$ de manera manual.

In [0]:
import numpy as np

x = np.array([1, 2, 3,4])
y = np.array([4, 5, 6])

print("\nx = ", x)
print("y = ", y)


x =  [1 2 3 4]
y =  [4 5 6]


>Ahora, se hará uso de los módulos **arange** y **linspace** del paquete **numpy** para crear de manera automática los arreglos $\mathbf{A1D}_{1\times n}$ y $\mathbf{B1D}_{1\times n}$. 

In [0]:
# importar el paquete [numpy]
import numpy as np

# Generar el arreglo A1D, usando el módulo numpy.arange
A1D = np.arange(0,10,0.5)
print("\nA1D = ", A1D)
print("dim/len(A1D) = ", len(A1D))
print("dim/A1D.shape = ", A1D.shape)
print(type(A1D),A1D.dtype)

# Generar el arreglo B1D, usando el módulo numpy.linspace
B1D = np.linspace(-5,5,19)
print("\nB1D = ", B1D)
print("dim/len(B1D) = ", len(B1D))
print("dim/B1D.shape = ", B1D.shape)
print(type(B1D),B1D.dtype)


A1D =  [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
dim/len(A1D) =  20
dim/A1D.shape =  (20,)
<class 'numpy.ndarray'> float64

B1D =  [-5.         -4.44444444 -3.88888889 -3.33333333 -2.77777778 -2.22222222
 -1.66666667 -1.11111111 -0.55555556  0.          0.55555556  1.11111111
  1.66666667  2.22222222  2.77777778  3.33333333  3.88888889  4.44444444
  5.        ]
dim/len(B1D) =  19
dim/B1D.shape =  (19,)
<class 'numpy.ndarray'> float64


### Arreglos de n dimensiones (nD)
> Los arreglos de n-dimensiones más comunes debido a su utilidad para representar problemas reales, son los de 2 y 3 dimensiones. Para empezar crearemos los arreglos:

#### Arreglos de dos dimensiones  $\mathbf{x2D}_{m\times n}$ y $\mathbf{y2D}_{m\times n}$ de manera manual.

In [0]:
import numpy as np
x2D = np.array([[1,2],[3,4]])
print("Arreglo de 2-dimensiones: 2 filas y 2 columnas")
print("\2D =\n ", x2D)
print("x2D[0,1] = ", x2D[0,1])
x2D[0,1]=999
print("\nx2D =\n ", x2D)

y2D = np.array([[2,3,4],[6,5,4]])
print("\nArreglo de 2-dimensiones: 2 filas y 3 columnas")
print("y2D = \n", y2D)
print("y2D[0,1] = ", y2D[0,1])
y2D[0,1]=999
print("\ny2D =\n ", y2D)

Arreglo de 2-dimensiones: 2 filas y 2 columnas
D =
  [[1 2]
 [3 4]]
x2D[0,1] =  2

x2D =
  [[  1 999]
 [  3   4]]

Arreglo de 2-dimensiones: 2 filas y 3 columnas
y2D = 
 [[2 3 4]
 [6 5 4]]
y2D[0,1] =  3

y2D =
  [[  2 999   4]
 [  6   5   4]]


#### Arreglos de dos dimensiones $(\mathbf{A2D}_{m\times n})$ y tres dimensiones $(\mathbf{A3D}_{t \times m\times n})$ dimensiones usando  los módulos **np.arange**, **np.linspace**, **np.reshape**, **np.zeros** y **np.ones**.

In [0]:
import numpy as np

print("Arreglo de 2-dimensiones: 3 filas y 4 columnas ")
A2D = np.arange(3*4).reshape(3,4)
print("\nA2D = \n", A2D)
print("\ndim/A2D.shape = ", A2D.shape)
print(type(A2D), A2D.dtype)

print("\nArreglo de 3-dimensiones: 3 niveles, 3 filas y 4 columnas ")
A3D = np.arange(3*3*4).reshape(3,3,4)
print("A3D = \n", A3D)
print("\ndim/A3D.shape = ", A3D.shape)
print(type(A3D), A3D.dtype)

Arreglo de 2-dimensiones: 3 filas y 4 columnas 

A2D = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

dim/A2D.shape =  (3, 4)
<class 'numpy.ndarray'> int64

Arreglo de 3-dimensiones: 3 niveles, 3 filas y 4 columnas 
A3D = 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]

dim/A3D.shape =  (3, 3, 4)
<class 'numpy.ndarray'> int64


## 9.2. Operaciones con matrices

Los arreglos de **numpy** permiten realizar operaciones de suma, resta, productor escalar (elemento a elemento)  producto vectorial. Para lo cual, es necesario que los arreglos cumplan las siguientes condiciones:
* Los arreglos deben tener las mismas dimensiones (suma, resta, producto aritmético y escalar)

* Para el producto vectorial de los arreglos $\mathbf{A}_{m \times n}$ y $\mathbf{B}_{s \times p}$, es necesario que $n=s$, esto es: el número de columnas de $\mathbf{A}$ tiene que ser igual al número de filas de $\mathbf{B}$.

#### Suma  y producto aritmético y escalar de arreglos de una dimensión

In [0]:
# importar el paquete [numpy]
import numpy as np

# Generar el arreglo A1D, usando el módulo numpy.arange
A1D = np.arange(0,10,1)
print("\nA1D = ", A1D)
print("dim/A1D.shape = ", A1D.shape)


# Generar el arreglo B1D, usando el módulo numpy.linspace
B1D = np.arange(10,20,1)
print("\nB1D = ", B1D)
print("dim/B1D.shape = ", B1D.shape)

print("\nSuma de arreglos")
S1D = A1D + B1D
print("S1D = A1D + B1D =", S1D)
print("dim/S1D.shape = ", S1D.shape)

print("\nProducto aitmético (*) de arreglos")
P1D = A1D*B1D
print("C1D = A1D + B1D =", P1D)
print("dim/C1D.shape = ", P1D.shape)

print("\nProducto escalar (np.dot) de arreglos")
dot1D = np.dot(A1D,B1D)
print("C1D = A1D + B1D =", dot1D)
print("dim/C1D.shape = ", dot1D.shape)


A1D =  [0 1 2 3 4 5 6 7 8 9]
dim/A1D.shape =  (10,)

B1D =  [10 11 12 13 14 15 16 17 18 19]
dim/B1D.shape =  (10,)

Suma de arreglos
S1D = A1D + B1D = [10 12 14 16 18 20 22 24 26 28]
dim/S1D.shape =  (10,)

Producto aitmético (*) de arreglos
C1D = A1D + B1D = [  0  11  24  39  56  75  96 119 144 171]
dim/C1D.shape =  (10,)

Producto escalar (np.dot) de arreglos
C1D = A1D + B1D = 735
dim/C1D.shape =  ()


#### Suma  y producto atrimético de arreglos de n-dimensiones
Las operaciones de suma y producto aritmético entre arreglos se da elemento a elemento, por lo que, es necesario que los arreglos presenten las mismas dimensiones.

In [0]:
import numpy as np

print("Arreglo de 2-dimensiones: 3 filas y 4 columnas ")
A2D = np.arange(3*4).reshape(3,4)
print("\nA2D = \n", A2D)
print("\ndim/A2D.shape = ", A2D.shape)

B2D = np.arange(0,12).reshape(3,4)
print("B2D = \n", B2D)
print("\ndim/A3D.shape = ", B2D.shape)

print("\n Producto aritmético de A2D y B2D")
M2D = A2D*B2D#np.dot(A2D, B2D)
print(M2D)

Arreglo de 2-dimensiones: 3 filas y 4 columnas 

A2D = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

dim/A2D.shape =  (3, 4)
B2D = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

dim/A3D.shape =  (3, 4)

 Producto aritmético de A2D y B2D
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


#### Producto escalar de arreglos de n-dimensiones
El producto esccalar de los arreglos $\mathbf{A}_{m \times n}$ y $\mathbf{B}_{n \times p}$ dará como resultado un nuevo arreglo $\mathbf{C}_{m \times p}$, siguiendo la definición del producto de matrices en matemáticas. 

## $$\mathbf{A}_{m \times n} + \mathbf{B}_{n \times p} = \mathbf{C}_{m\times p}$$
Donde el número de columnas de $\mathbf{A}$ debe ser igual al número de filas de $\mathbf{B}$.

In [0]:
import numpy as np

print("Arreglo de 2-dimensiones: 3 filas y 4 columnas ")
A2D = np.arange(3*4).reshape(3,4)
print("\nA2D = \n", A2D)
print("\ndim/A2D.shape = ", A2D.shape)

B2D = np.arange(0,12).reshape(4,3)
print("B2D = \n", B2D)
print("\ndim/B2D.shape = ", B2D.shape)


print("\nProducto escalar: \nC2D = np.dot(A2D,2D)")
C2D = np.dot(A2D, B2D)
print(C2D)
print("\ndim/C2D.shape = ", C2D.shape)

Arreglo de 2-dimensiones: 3 filas y 4 columnas 

A2D = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

dim/A2D.shape =  (3, 4)
B2D = 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

dim/B2D.shape =  (4, 3)

Producto escalar: 
C2D = np.dot(A2D,2D)
[[ 42  48  54]
 [114 136 158]
 [186 224 262]]

dim/C2D.shape =  (3, 3)


## 9.4. Indexación de arreglos
Una de las bondades que presentan los arreglos de **numpy** es, la posibilidad de acceder y asignar cada elemento de un arreglo de la misma forma que las listas de Python. En la siguiente figura se presenta las diferentes formas para acceder a uno ó más elementos de un arreglo.

<img src="https://raw.githubusercontent.com/ryali93/UNMSM_programacion2019-1/master/jupyter/img/numpy_indexing.png" height="400" width="400">

In [0]:
import numpy as np # Importar paquete numpy como np
f1 = list(range(0,6)); f2 = np.arange(10,16); f3 = np.arange(20,26);f4 = np.arange(30,36); f5 = np.arange(40,46); f6 = np.arange(50,56)
a = np.array([f1,f2,f3,f4,f5,f6])
         
print("a =\n ", a)
print("\ndim(a) = ", a.shape)
print("ndim(a) = ", a.ndim)
print("\na[0,3:5] = ", a[0,3:5])
print("\na[4:,4:] = \n", a[4:,4:])
print("\na[:,2] = ", a[:,2])
print("\na[2::2,::2] = \n", a[2::2,::2])

a =
  [[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]

dim(a) =  (6, 6)
ndim(a) =  2

a[0,3:5] =  [3 4]

a[4:,4:] = 
 [[44 45]
 [54 55]]

a[:,2] =  [ 2 12 22 32 42 52]

a[2::2,::2] = 
 [[20 22 24]
 [40 42 44]]


#### Indexación usando control de flujos y condicionales

In [0]:
import numpy as np # Importar paquete numpy como np
f1 = list(range(0,6)); f2 = np.arange(10,16); f3 = np.arange(20,26)
f4 = np.arange(30,36); f5 = np.arange(40,46); f6 = np.arange(50,56)
a = np.array([f1,f2,f3,f4,f5,f6])
print(a)

nrows, ncols = a.shape

for irow in range(nrows):
    for icol in range(ncols):
        if a[irow,icol]%3==0:
            a[irow,icol]=999
        else:pass

print("\n",a)
            


[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]

 [[999   1   2 999   4   5]
 [ 10  11 999  13  14 999]
 [ 20 999  22  23 999  25]
 [999  31  32 999  34  35]
 [ 40  41 999  43  44 999]
 [ 50 999  52  53 999  55]]


## 9.5. Manipulación de formas
**Numpy** posee el método **numpy.ravels** que permite convertir un arreglo 2D en un arreglo de 1D con la finalidad de modificar la forma del arreglo. En ocasiones este proceso es conveniente para realizar el procesamiento de los datos de manera más eficiente.

In [0]:
### import numpy as np # Importar paquete numpy como np
f1 = list(range(0,6)); f2 = np.arange(10,16); f3 = np.arange(20,26)
f4 = np.arange(30,36); f5 = np.arange(40,46); f6 = np.arange(50,56)
a = np.array([f1,f2,f3,f4,f5,f6])
             
print("a =\n ", a)
print("dim/a = ", a.shape)

a = a.ravel()
print("a =\n ", a)
print("dim/a = ", a.shape)

for i in range(len(a)):
     if a[i]%3==0:
            a[i]=999

a=a.reshape(4,9)
print("a =\n ", a)
print("dim/a = ", a.shape)
            


a =
  [[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
dim/a =  (6, 6)
a =
  [ 0  1  2  3  4  5 10 11 12 13 14 15 20 21 22 23 24 25 30 31 32 33 34 35
 40 41 42 43 44 45 50 51 52 53 54 55]
dim/a =  (36,)
a =
  [[999   1   2 999   4   5  10  11 999]
 [ 13  14 999  20 999  22  23 999  25]
 [999  31  32 999  34  35  40  41 999]
 [ 43  44 999  50 999  52  53 999  55]]
dim/a =  (4, 9)


## 9.6. Apilación de matrices

**Numpy** posee el módulo **numpy.concatenate** que permite concatenar arreglos/matrices a través de los ejes de las filas **(axis=0)** y columnas **(axis=1)** como se ilustra en la siguiente figura.
<img src="https://raw.githubusercontent.com/ryali93/UNMSM_programacion2019-1/master/jupyter/img/axis_array.png" height="150" width="150">

In [0]:
import numpy as np # Importar paquete numpy como np
f1 = list(range(0,6)); f2 = np.arange(10,16); f3 = np.arange(20,26)
f4 = np.arange(30,36); f5 = np.arange(40,46); f6 = np.arange(50,56)

a =np.array([f1,f2])
print("a = \n",a)
print(type(a))

b =np.array([f3,f4])
print("b = \n",b)
print(type(b))

print("\napilando en el axis=0")
cc_axis0 = np.concatenate((a,b), axis=0)
print("cc_axis0 = \n",cc_axis0)
print(type(cc_axis0))

print("\napilando en el axis=1")
cc_axis1 = np.concatenate((a,b), axis=1)
print("\ncc_axis1 = \n",cc_axis1)
print(type(cc_axis1))

a = 
 [[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]]
<class 'numpy.ndarray'>
b = 
 [[20 21 22 23 24 25]
 [30 31 32 33 34 35]]
<class 'numpy.ndarray'>

apilando en el axis=0
cc_axis0 = 
 [[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]]
<class 'numpy.ndarray'>

apilando en el axis=1

cc_axis1 = 
 [[ 0  1  2  3  4  5 20 21 22 23 24 25]
 [10 11 12 13 14 15 30 31 32 33 34 35]]
<class 'numpy.ndarray'>


## 9.7. Introducción al algebra lineal

El **algebra lineal** es un de las herramientas matemáticas más utilizadas para el procesamiento y análisis de datos (machine learning, data mining y redes neuronales).

Debido al avance de la tecnología, la capacidad y la velocidad con la que se genera datos en diversas actividades y campos, el algebra lineal es utilizada en diferentes ramas de la ciencia (investigación, ingeniería, y finanzas).
En Python dentro del Paquete **numpy** se encuentra el módulo **numpy.linalg** el cual permite trabajar con sistemas de ecuaciones lineales, matrices y vectores.

### 9.7.1 Matrices

**Transpuesta de una matriz**

Sea $\mathbf{A}$ una matriz con **m** filas y **n** columnas. La matriz transpuesta, denotada matemáticamente con $\mathbf{A}^{t}$, está dada por:

## $\mathbf{A}_{ji}^{t} = \mathbf{A}_{ij}$

En donde el elemento ${a}_{ij}$ de la matriz original $\mathbf{A}$ se convertirá en el elemento ${a}_{ji}$ de la matriz transpuesta $\mathbf{A}^{t}$.

In [0]:
import numpy as np

A = np.arange(30).reshape(5,6)
     
def print_r(matriz):
    for fila in matriz:
        print(fila)
    
def transpuesta1(matriz):    
    nrows, ncols = np.shape(matriz)
    return [[matriz[j][i] for j in np.arange(nrows)] for i in np.arange(ncols)]     

def transpuesta2(matriz):    
    nrows, ncols = np.shape(matriz)
    matrizT = np.zeros((ncols, nrows))
    for i in range(4):
        for j in range(3):
            matrizT[j][i] = matriz[i][j]
    return matrizT

print("Original(A)")
print_r(A)
print("\nTRANSPUESTA(A)")
print_r(transpuesta1(A))
print(type(transpuesta1(A)))

print("\nTRANSPUESTA(A) usando numpy")
#print_r(A.transpose())
print_r(A.T)
print(type(A.transpose()))

Original(A)
[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]

TRANSPUESTA(A)
[0, 6, 12, 18, 24]
[1, 7, 13, 19, 25]
[2, 8, 14, 20, 26]
[3, 9, 15, 21, 27]
[4, 10, 16, 22, 28]
[5, 11, 17, 23, 29]
<class 'list'>

TRANSPUESTA(A) usando numpy
[ 0  6 12 18 24]
[ 1  7 13 19 25]
[ 2  8 14 20 26]
[ 3  9 15 21 27]
[ 4 10 16 22 28]
[ 5 11 17 23 29]
<class 'numpy.ndarray'>


### 9.7.2. Vectores en el espacio 2D y 3D
Sean $\mathbf{a}$ y $\mathbf{b}$ dos vectores de un mismo plano como se muestra en la siguiente figura.

<img src="https://raw.githubusercontent.com/ryali93/UNMSM_programacion2019-1/master/jupyter/img/ab.png" height="150" width="150">

Donde:
$\mathbf{a} = (a_{1}, a_{2}, a_{3})$ y $\mathbf{b} = (b_{1}, b_{2}, b_{3})$

**Producto escalar**

$\mathbf{a}.\mathbf{b} = numpy.dot(a,b) = a_{1}b_{1} + a_{2}b_{2} + a_{3}b_{3}$

** Producto vectorial**

$\mathbf{a} \times \mathbf{b} = numpy.cross(a,b) $

In [0]:
import numpy as np

a = np.array([3,4,0])
b = np.array([3,5,0])

# producto escalar 
ab = np.dot(a,b)
print("a.b = ", ab)

# producto vectorial 
axb = np.cross(a,b)
print("a x b = ", axb)

a.b =  29
a x b =  [0 0 3]


### 9.7.3. Sistema de ecuaciones lineales

Sea el sistema de ecuaciones lineales:

### $$\mathbf{x} + \mathbf{y} + \mathbf{z} = -1$$
### $$\mathbf{x} + 2\mathbf{y} + 2\mathbf{z} = 0$$
### $$2\mathbf{x} + \mathbf{y} - \mathbf{z} = 1$$


Donde la representación matricial está dado por:

$$
\left[ \begin{array}{ccc}
  1 & 1 & 1\\
  1 & 2 & 2\\
  2 & 1 &-1 \\
  \end{array}\right] \left[ \begin{array}{ccc}
  x \\
  y \\
  z \\
  \end{array}\right]  = \left[ \begin{array}{ccc}
  -1 \\
  0 \\
  1 \\
  \end{array}\right] 
$$

Por lo tanto la forma matricial del sistema de ecuaciones lineales presenta la siguiente forma:

## $\mathbf{a}\mathbf{x} = \mathbf{b} \hspace{3cm} (\alpha)$
Si el $det(\mathbf{a})\not=0$ entonces la matriz **a** tiene inversa y es $\mathbf{a}^{-1}$. y se cumple la siguiente:

## $\mathbf{a}\mathbf{a}^{-1} = I$

Luego si multiplicamos ambos miembros de la ecuación $(\alpha)$ por $\mathbf{a}^{-1}$, tendremos lo siguiente:

## $\mathbf{a} \mathbf{a}^{-1}\mathbf{x} = \mathbf{a}^{-1}\mathbf{b}$

## $\mathbf{I}\mathbf{x} = \mathbf{a}^{-1}\mathbf{b}$

## $\mathbf{x} = \mathbf{a}^{-1}\mathbf{b} \hspace{3cm}(\beta)$ 

Por lo tanto, la ecuación $(\mathbf{\beta})$ también porporciona las soluciones de un sistema de ecuaciones lineales.


In [0]:
import numpy as np
"""
El sistema de ecuaciones lineales tiene solución si se cumple:
    det(a) != 0
Caso contrario el sistema de ecuaciones no tiene solución.
"""

a = np.array([[1,1,-1], [1,2,2], [2,1,-1]])
b = np.array([-1, 0, 1])

# determinante de (a)
print("determinante de (a):")
det_a = np.linalg.det(a)
print("det_a = ", det_a)

# Determinar las soluciones del sistema lineal de ecuaciones
x = np.linalg.solve(a,b)
print("\nLas soluciones son:\n[x0, y0, z0]\n", x)

#Segunda forma
inv_a = np.linalg.inv(a)
print(a)
print("\n",inv_a)

xx = np.dot(inv_a,b)
print(xx)

determinante de (a):
det_a =  3.999999999999999

Las soluciones son:
[x0, y0, z0]
 [ 2. -2.  1.]
[[ 1  1 -1]
 [ 1  2  2]
 [ 2  1 -1]]

 [[-1.    0.    1.  ]
 [ 1.25  0.25 -0.75]
 [-0.75  0.25  0.25]]
[ 2. -2.  1.]


In [0]:
import numpy as np

x = np.array([1, 2, 3,4])
y = np.array([4, 5, 6])

print("\nx = ", x)
print("y = ", y)


x =  [1 2 3 4]
y =  [4 5 6]
